import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import Link from 'next/link';
import { Heart } from "@/components/icon/heart";
import { Gallery } from "@/components/icon/gallery";
import { Album } from "@/components/icon/album";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function SideMenu() {
  //const { folders } = (await cloudinary.v2.api.root_folders()) as {
    //folders: Folder[];
  //};

  return (
    <div className="pb-12 w-1/5">
      <div className="space-y-4 py-4">
        <div className="px-3 py-2">
          <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
            Manage
          </h2>
          <div className="space-y-1">

            <Button asChild variant="ghost" className="w-full justify-start flex gap-2" >
              <Link href = "/gallery">
                <Gallery/>
                Gallery
              </Link>
            </Button>


            <Button variant="ghost" className="w-full justify-start flex gap-2" >
                <Album/>
                Albums
            </Button>
            
            <Button asChild variant="ghost" className="w-full justify-start flex gap-2">
              <Link href="/favorites">
                <Heart/>
                Favorites
              </Link>
            </Button>

          </div>
        </div>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="border-b">
          <div className="flex h-16 items-center px-4 container mx-auto">
            Photos
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage
                  src="https://github.com/shadcn.png"
                  alt="@shadcn"
                />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>

        <div className="flex">
          <SideMenu />

          <div className="w-full px-5 pt-8">
            {children}
          </div>
        </div>

      </body>
    </html>
  );
}
